Repository otakaran/mustang-messenger, pull requests merged in 2021-02, with the labels that each got.

#17 Updated readme with style guide
  .deepsource.toml
  README.md
  README.old.md
Labels: documentation

#19 Signup component
  package-lock.json
  package.json
  src/App.js
  src/Login.js
  src/Signup.js
  src/css/index.css
  src/header.js
  src/index.js
  src/landing.js
Labels: enhancement

#23 Login backend is functional
  package-lock.json
  package.json
  src/App.js
  src/Fire.js
  src/Login.js
  src/MessagesPage.js
  src/Signup.js
Labels: enhancement

#35 Sign out implemented in backend
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.js
  src/Messaging.js
  src/fire/Fire.js
  src/fire/loginFire.js
  src/fire/logoutFire.js
  src/fire/sendMessageFire.js
  src/fire/signupFire.js
  src/fire/userFire.js
  src/testSignOut.js
Labels: enhancement, help wanted
